all:
	clear
	g++ -Wall -fPIC --std=c++11 -I/usr/include/qt5 main.cpp mainwindow.cpp container.cpp widgetajouter.cpp widgetracine.cpp widgettriplet.cpp widgetregle.cpp widgetreglesimple.cpp widgetregledouble.cpp widgetregleaff.cpp -l Qt5Widgets -l Qt5Core -l Qt5Gui -o NomApp

launch:
	./NomApp